export const TRIGGER_TYPES = [
  {
    triggerType: "manual.command_center",
    displayName: "Manual Command Center",
    purpose: "Preview a local operator action requested from Command Center.",
    sourceSystem: "command_center_v2",
    enabledNow: true,
    executionAllowed: false,
    dryRunOnly: true,
    requiresApproval: false,
    allowedScopes: ["PROJECT_CHANGE", "NEXUS_OS_CHANGE", "CROSS_CUTTING_CHANGE"],
    allowedModes: ["local-private", "demo", "test"],
    requiredCapabilities: ["command_center", "trigger_gateway_schema"],
    forbiddenActions: ["provider_call", "external_network", "db_write", "project_mutation", "worker_execution"],
    evidenceRequired: true,
    auditRequired: true,
    costPolicyRequired: true,
    dedupeRequired: true,
    rateLimitRequired: true,
  },
  {
    triggerType: "manual.command_palette",
    displayName: "Manual Command Palette",
    purpose: "Preview a command-palette operator intent without executing it.",
    sourceSystem: "command_palette",
    enabledNow: true,
    executionAllowed: false,
    dryRunOnly: true,
    requiresApproval: false,
    allowedScopes: ["PROJECT_CHANGE", "NEXUS_OS_CHANGE", "CROSS_CUTTING_CHANGE"],
    allowedModes: ["local-private", "demo", "test"],
    requiredCapabilities: ["command_palette", "trigger_gateway_schema"],
    forbiddenActions: ["provider_call", "external_network", "db_write", "project_mutation", "worker_execution"],
    evidenceRequired: true,
    auditRequired: true,
    costPolicyRequired: true,
    dedupeRequired: true,
    rateLimitRequired: true,
  },
  {
    triggerType: "schedule.cron_preview",
    displayName: "Cron Preview",
    purpose: "Describe a future schedule trigger without registering timers or workers.",
    sourceSystem: "scheduler_preview",
    enabledNow: false,
    executionAllowed: false,
    dryRunOnly: true,
    requiresApproval: true,
    allowedScopes: ["PROJECT_CHANGE", "NEXUS_OS_CHANGE"],
    allowedModes: ["local-private", "test"],
    requiredCapabilities: ["trigger_gateway_schema", "rate_limit_policy", "cost_policy"],
    forbiddenActions: ["timer_registration", "worker_execution", "provider_call", "external_network", "db_write"],
    evidenceRequired: true,
    auditRequired: true,
    costPolicyRequired: true,
    dedupeRequired: true,
    rateLimitRequired: true,
  },
  {
    triggerType: "repo.github_event_preview",
    displayName: "GitHub Event Preview",
    purpose: "Map repository events to dry-run NEXUS actions without GitHub API calls.",
    sourceSystem: "github_preview",
    enabledNow: false,
    executionAllowed: false,
    dryRunOnly: true,
    requiresApproval: true,
    allowedScopes: ["PROJECT_CHANGE"],
    allowedModes: ["local-private", "test"],
    requiredCapabilities: ["trigger_gateway_schema", "scope_boundary", "dedupe_policy"],
    forbiddenActions: ["github_api_call", "webhook_listener", "credential_use", "pr_mutation", "project_mutation"],
    evidenceRequired: true,
    auditRequired: true,
    costPolicyRequired: true,
    dedupeRequired: true,
    rateLimitRequired: true,
  },
  {
    triggerType: "ticket.jira_preview",
    displayName: "Jira Preview",
    purpose: "Map Jira issue events to dry-run NEXUS actions without Jira integration.",
    sourceSystem: "jira_preview",
    enabledNow: false,
    executionAllowed: false,
    dryRunOnly: true,
    requiresApproval: true,
    allowedScopes: ["PROJECT_CHANGE"],
    allowedModes: ["local-private", "test"],
    requiredCapabilities: ["trigger_gateway_schema", "privacy_classification", "scope_boundary"],
    forbiddenActions: ["jira_api_call", "credential_use", "ticket_mutation", "webhook_listener"],
    evidenceRequired: true,
    auditRequired: true,
    costPolicyRequired: true,
    dedupeRequired: true,
    rateLimitRequired: true,
  },
  {
    triggerType: "ticket.linear_preview",
    displayName: "Linear Preview",
    purpose: "Map Linear issue events to dry-run NEXUS actions without Linear integration.",
    sourceSystem: "linear_preview",
    enabledNow: false,
    executionAllowed: false,
    dryRunOnly: true,
    requiresApproval: true,
    allowedScopes: ["PROJECT_CHANGE"],
    allowedModes: ["local-private", "test"],
    requiredCapabilities: ["trigger_gateway_schema", "privacy_classification", "scope_boundary"],
    forbiddenActions: ["linear_api_call", "credential_use", "ticket_mutation", "webhook_listener"],
    evidenceRequired: true,
    auditRequired: true,
    costPolicyRequired: true,
    dedupeRequired: true,
    rateLimitRequired: true,
  },
  {
    triggerType: "chat.slack_preview",
    displayName: "Slack Preview",
    purpose: "Parse future Slack commands without bot tokens, webhooks, or channel storage.",
    sourceSystem: "slack_preview",
    enabledNow: false,
    executionAllowed: false,
    dryRunOnly: true,
    requiresApproval: true,
    allowedScopes: ["PROJECT_CHANGE", "NEXUS_OS_CHANGE"],
    allowedModes: ["local-private", "test"],
    requiredCapabilities: ["trigger_gateway_schema", "scope_confirmation", "approval_policy"],
    forbiddenActions: ["slack_api_call", "bot_token_use", "webhook_listener", "channel_storage"],
    evidenceRequired: true,
    auditRequired: true,
    costPolicyRequired: true,
    dedupeRequired: true,
    rateLimitRequired: true,
  },
  {
    triggerType: "chat.teams_preview",
    displayName: "Teams Preview",
    purpose: "Parse future Teams commands without bot tokens, webhooks, or channel storage.",
    sourceSystem: "teams_preview",
    enabledNow: false,
    executionAllowed: false,
    dryRunOnly: true,
    requiresApproval: true,
    allowedScopes: ["PROJECT_CHANGE", "NEXUS_OS_CHANGE"],
    allowedModes: ["local-private", "test"],
    requiredCapabilities: ["trigger_gateway_schema", "scope_confirmation", "approval_policy"],
    forbiddenActions: ["teams_api_call", "bot_token_use", "webhook_listener", "channel_storage"],
    evidenceRequired: true,
    auditRequired: true,
    costPolicyRequired: true,
    dedupeRequired: true,
    rateLimitRequired: true,
  },
  {
    triggerType: "webhook.api_preview",
    displayName: "API Webhook Preview",
    purpose: "Describe a future API webhook trigger without opening a receiver.",
    sourceSystem: "api_webhook_preview",
    enabledNow: false,
    executionAllowed: false,
    dryRunOnly: true,
    requiresApproval: true,
    allowedScopes: ["PROJECT_CHANGE", "NEXUS_OS_CHANGE", "CROSS_CUTTING_CHANGE"],
    allowedModes: ["local-private", "test"],
    requiredCapabilities: ["trigger_gateway_schema", "scope_boundary", "dedupe_policy", "rate_limit_policy"],
    forbiddenActions: ["webhook_listener", "external_network", "credential_use", "worker_execution", "project_mutation"],
    evidenceRequired: true,
    auditRequired: true,
    costPolicyRequired: true,
    dedupeRequired: true,
    rateLimitRequired: true,
  },
];

export function getTriggerTypes() {
  return TRIGGER_TYPES.map((triggerType) => ({ ...triggerType }));
}

export function validateTriggerType(triggerType) {
  const errors = [];
  const requiredFields = [
    "triggerType",
    "displayName",
    "purpose",
    "sourceSystem",
    "enabledNow",
    "executionAllowed",
    "dryRunOnly",
    "requiresApproval",
    "allowedScopes",
    "allowedModes",
    "requiredCapabilities",
    "forbiddenActions",
    "evidenceRequired",
    "auditRequired",
    "costPolicyRequired",
    "dedupeRequired",
    "rateLimitRequired",
  ];

  for (const field of requiredFields) {
    if (!(field in triggerType)) errors.push(`Missing field: ${field}`);
  }
  if (triggerType.executionAllowed !== false) errors.push("Trigger execution must be disabled");
  if (triggerType.dryRunOnly !== true) errors.push("Trigger must be dry-run only");
  if (!Array.isArray(triggerType.allowedScopes) || triggerType.allowedScopes.length === 0) {
    errors.push("Trigger must define allowed scopes");
  }
  if (!Array.isArray(triggerType.forbiddenActions) || triggerType.forbiddenActions.length === 0) {
    errors.push("Trigger must define forbidden actions");
  }
  return { valid: errors.length === 0, errors };
}
