import { createMemoryItem } from "./memorySchema.js";

export const SAFE_MEMORY_FIXTURES = [
  createMemoryItem({
    memoryId: "mem-os-roadmap-p46",
    scope: "nexus_os",
    agentId: "NEXUS",
    type: "roadmap_status",
    summary: "P46 introduces scoped memory as metadata-only architecture before runtime injection.",
    source: "P46 roadmap status",
    classification: "os_internal",
    allowedAgents: ["NEXUS", "SHEPHERD", "AUDITOR", "WARDEN"],
    forbiddenModes: ["demo", "public"],
    freshness: "fresh",
    confidence: 0.92,
    lastVerifiedAt: "2026-05-15T00:00:00.000Z",
    evidenceIds: ["memory-scope-model-report"],
  }),
  createMemoryItem({
    memoryId: "mem-project-private-summary",
    scope: "project",
    projectId: "private-project",
    agentId: "SHEPHERD",
    type: "project_context",
    summary: "Private Project uses project-scoped summaries and must not leak into demo mode.",
    source: "Project context metadata",
    classification: "project_private",
    allowedAgents: ["SHEPHERD", "CORE", "AUDITOR", "WARDEN", "SENTINEL"],
    forbiddenModes: ["demo", "public"],
    freshness: "fresh",
    confidence: 0.86,
    lastVerifiedAt: "2026-05-15T00:00:00.000Z",
    evidenceIds: ["project-registry-final-validation"],
  }),
  createMemoryItem({
    memoryId: "mem-task-governed-build",
    scope: "task",
    projectId: "private-project",
    missionId: "private-project-governed-build-mission",
    taskId: "task-governed-build-summary",
    agentId: "CORE",
    type: "task_summary",
    summary: "Controlled implementation tasks require scoped context, evidence, and validation gates.",
    source: "Task metadata summary",
    classification: "local_private",
    allowedAgents: ["CORE", "AUDITOR", "SENTINEL", "WARDEN"],
    forbiddenModes: ["demo", "public"],
    freshness: "fresh",
    confidence: 0.82,
    lastVerifiedAt: "2026-05-15T00:00:00.000Z",
    evidenceIds: ["controlled-implementation-workflow"],
  }),
  createMemoryItem({
    memoryId: "mem-session-local-private",
    scope: "session",
    projectId: "private-project",
    agentId: "NEXUS",
    type: "session_boundary",
    summary: "Local-private session memory is a temporary summary and should expire before reuse.",
    source: "Session metadata summary",
    classification: "local_private",
    allowedAgents: ["NEXUS", "SHEPHERD"],
    forbiddenModes: ["demo", "public"],
    freshness: "unknown",
    confidence: 0.7,
    expiresAt: "2026-05-22T00:00:00.000Z",
    evidenceIds: [],
  }),
];

export function getSafeMemoryFixtures() {
  return SAFE_MEMORY_FIXTURES.map((item) => ({ ...item }));
}
