export const OPERATOR_ACTION_CATALOG = [
  {
    actionId: "plan",
    intentType: "plan_mission",
    label: "Plan Mission",
    routeTarget: "/command-center",
    requiredCapabilities: ["missionComposer", "missionActionBridge"],
    riskLevel: "low",
    blockedReason: "Requires governed mission composer or action bridge.",
    nextAction: "Open Mission Control and preview a governed mission plan.",
  },
  {
    actionId: "review",
    intentType: "review_plan",
    label: "Review Work",
    routeTarget: "/command-center/workbench",
    requiredCapabilities: ["agentWorkbench", "humanReview"],
    riskLevel: "medium",
    blockedReason: "Requires an activated task or reviewable plan.",
    nextAction: "Open Agent Workbench for review context.",
  },
  {
    actionId: "qa",
    intentType: "run_quality_gate_preview",
    label: "Run QA Gate",
    routeTarget: "/command-center/tests",
    requiredCapabilities: ["controlledValidation", "testSuiteManager"],
    riskLevel: "medium",
    blockedReason: "Requires test suite manager or controlled validation bridge.",
    nextAction: "Open Test Center and inspect validation prerequisites.",
  },
  {
    actionId: "fix",
    intentType: "prepare_fix_preview",
    label: "Propose Fix",
    routeTarget: "/command-center/implementation",
    requiredCapabilities: ["controlledImplementation", "failingEvidence"],
    riskLevel: "high",
    blockedReason: "Requires failing validation evidence and controlled mutation later.",
    nextAction: "Open Implementation and inspect fix readiness.",
  },
  {
    actionId: "ship",
    intentType: "prepare_release_preview",
    label: "Prepare Ship",
    routeTarget: "/command-center/release",
    requiredCapabilities: ["releaseActionBridge"],
    riskLevel: "high",
    blockedReason: "Requires release action bridge.",
    nextAction: "Open Release Control and inspect release blockers.",
  },
  {
    actionId: "guard",
    intentType: "guard_scope",
    label: "Guard Scope",
    routeTarget: "/command-center/safety",
    requiredCapabilities: ["scopeBoundary"],
    riskLevel: "medium",
    blockedReason: "",
    nextAction: "Open Safety Center for scope boundary preview.",
  },
  {
    actionId: "freeze",
    intentType: "freeze_scope",
    label: "Freeze Workspace",
    routeTarget: "/command-center/workers",
    requiredCapabilities: ["runtimeLocks"],
    riskLevel: "high",
    blockedReason: "Requires runtime lock controls.",
    nextAction: "Inspect concurrency locks preview. Runtime freeze is not enabled yet.",
  },
  {
    actionId: "explain",
    intentType: "explain_status",
    label: "Explain Current State",
    routeTarget: "/command-center",
    requiredCapabilities: ["commandPalette"],
    riskLevel: "low",
    blockedReason: "",
    nextAction: "Show read-only current state summary.",
  },
  {
    actionId: "open",
    intentType: "open_page",
    label: "Open Page",
    routeTarget: "/command-center",
    requiredCapabilities: ["commandPalette"],
    riskLevel: "low",
    blockedReason: "",
    nextAction: "Navigate to the matched Command Center page.",
  },
];

export function getOperatorActionForIntent(intentType) {
  return OPERATOR_ACTION_CATALOG.find((action) => action.intentType === intentType) || null;
}
