/**
 * test-suite/osTestSuites.js
 * Preview-only OS-scoped test suite records for NEXUS OS infrastructure layers.
 * All suites have executionEnabled: false and are display-only.
 * No test execution occurs from this module.
 */

import { normalizeTestSuiteRecord, validateTestSuiteRecord } from "./testRegistrySchema.js";

/**
 * Build the list of OS test suite records.
 * Returns an array of normalized suite records.
 */
export function buildOsTestSuites(context = {}) {
  const suites = [
    {
      suiteId: "os-command-center-route-tests",
      osScope: "nexus-os",
      scope: "os",
      layer: "ui",
      tool: "playwright",
      commandPreview: "npx playwright test dashboard/tests/",
      description: "Command Center route smoke tests: verify all routes render without error.",
      requiresApproval: false,
      requiresRunner: false,
      riskLevel: "low",
      costClass: "low",
      evidenceTypes: ["playwright-report"],
      ownerAgent: "AUDITOR",
      changedFilePatterns: ["dashboard/**"],
      forbiddenInDemo: false,
      dataClassification: "public",
      executionEnabled: false,
      allowedInMode: ["controlled"],
      status: "ready",
    },
    {
      suiteId: "os-public-private-demo-boundary-checks",
      osScope: "nexus-os",
      scope: "os",
      layer: "policy",
      tool: "node-script",
      commandPreview: "node scripts/check-public-safety.js && node scripts/check-private-project-mode.js",
      description: "Public/private/demo boundary checks: verify that private data does not leak into demo or public modes.",
      requiresApproval: false,
      requiresRunner: false,
      riskLevel: "low",
      costClass: "free",
      evidenceTypes: ["boundary-check-report"],
      ownerAgent: "AUDITOR",
      changedFilePatterns: ["policy/**", "private-mode/**", "demo/**"],
      forbiddenInDemo: false,
      dataClassification: "public",
      executionEnabled: false,
      allowedInMode: ["preview", "controlled"],
      status: "ready",
    },
    {
      suiteId: "os-project-registry-checks",
      osScope: "nexus-os",
      scope: "os",
      layer: "policy",
      tool: "node-script",
      commandPreview: "node scripts/check-project-registry-final-validation.js",
      description: "Project registry checks: validate registry schema, profile loader, and capability matrix.",
      requiresApproval: false,
      requiresRunner: false,
      riskLevel: "low",
      costClass: "free",
      evidenceTypes: ["registry-check-report"],
      ownerAgent: "AUDITOR",
      changedFilePatterns: ["project-registry/**"],
      forbiddenInDemo: false,
      dataClassification: "public",
      executionEnabled: false,
      allowedInMode: ["preview", "controlled"],
      status: "ready",
    },
    {
      suiteId: "os-scope-boundary-checks",
      osScope: "nexus-os",
      scope: "os",
      layer: "policy",
      tool: "node-script",
      commandPreview: "node scripts/check-scope-boundary-final-validation.js",
      description: "Scope boundary checks: verify OS/project boundary classification and export safety.",
      requiresApproval: false,
      requiresRunner: false,
      riskLevel: "low",
      costClass: "free",
      evidenceTypes: ["scope-boundary-report"],
      ownerAgent: "AUDITOR",
      changedFilePatterns: ["scope-boundary/**"],
      forbiddenInDemo: false,
      dataClassification: "public",
      executionEnabled: false,
      allowedInMode: ["preview", "controlled"],
      status: "ready",
    },
    {
      suiteId: "os-agent-boundary-checks",
      osScope: "nexus-os",
      scope: "os",
      layer: "policy",
      tool: "node-script",
      commandPreview: "node scripts/check-agent-registry-final-validation.js",
      description: "Agent boundary checks: validate agent registry schema, capability matrix, and boundaries.",
      requiresApproval: false,
      requiresRunner: false,
      riskLevel: "low",
      costClass: "free",
      evidenceTypes: ["agent-boundary-report"],
      ownerAgent: "AUDITOR",
      changedFilePatterns: ["agent-registry/**"],
      forbiddenInDemo: false,
      dataClassification: "public",
      executionEnabled: false,
      allowedInMode: ["preview", "controlled"],
      status: "ready",
    },
    {
      suiteId: "os-memory-trusted-context-checks",
      osScope: "nexus-os",
      scope: "os",
      layer: "runtime",
      tool: "node-script",
      commandPreview: "node scripts/check-scoped-memory-final-validation.js && node scripts/check-trusted-context-final-validation.js",
      description: "Scoped memory and trusted context checks: validate data sources, freshness, lineage, and access policy.",
      requiresApproval: false,
      requiresRunner: false,
      riskLevel: "low",
      costClass: "free",
      evidenceTypes: ["memory-check-report", "trusted-context-report"],
      ownerAgent: "AUDITOR",
      changedFilePatterns: ["memory/**", "trusted-context/**"],
      forbiddenInDemo: false,
      dataClassification: "public",
      executionEnabled: false,
      allowedInMode: ["preview", "controlled"],
      status: "ready",
    },
    {
      suiteId: "os-mesh-checks",
      osScope: "nexus-os",
      scope: "os",
      layer: "runtime",
      tool: "node-script",
      commandPreview: "node scripts/check-governed-agentic-mesh.js",
      description: "Governed agent mesh checks: validate message contracts, rooms, handoffs, and context sync.",
      requiresApproval: false,
      requiresRunner: false,
      riskLevel: "low",
      costClass: "free",
      evidenceTypes: ["mesh-check-report"],
      ownerAgent: "AUDITOR",
      changedFilePatterns: ["agent-mesh/**"],
      forbiddenInDemo: false,
      dataClassification: "public",
      executionEnabled: false,
      allowedInMode: ["preview", "controlled"],
      status: "ready",
    },
    {
      suiteId: "os-skill-registry-checks",
      osScope: "nexus-os",
      scope: "os",
      layer: "policy",
      tool: "node-script",
      commandPreview: "node scripts/check-skill-registry.js",
      description: "Skill registry checks: validate skill profiles, templates, test requirements, and ownership.",
      requiresApproval: false,
      requiresRunner: false,
      riskLevel: "low",
      costClass: "free",
      evidenceTypes: ["skill-registry-report"],
      ownerAgent: "AUDITOR",
      changedFilePatterns: ["skills-registry/**"],
      forbiddenInDemo: false,
      dataClassification: "public",
      executionEnabled: false,
      allowedInMode: ["preview", "controlled"],
      status: "ready",
    },
    {
      suiteId: "os-hook-registry-checks",
      osScope: "nexus-os",
      scope: "os",
      layer: "policy",
      tool: "node-script",
      commandPreview: "node scripts/check-hook-registry.js",
      description: "Hook registry checks: validate hook definitions, guard decisions, trigger previews, and loop risk detection.",
      requiresApproval: false,
      requiresRunner: false,
      riskLevel: "low",
      costClass: "free",
      evidenceTypes: ["hook-registry-report"],
      ownerAgent: "AUDITOR",
      changedFilePatterns: ["hooks/**", "hook-registry/**"],
      forbiddenInDemo: false,
      dataClassification: "public",
      executionEnabled: false,
      allowedInMode: ["preview", "controlled"],
      status: "ready",
    },
    {
      suiteId: "os-tool-mcp-governance-checks",
      osScope: "nexus-os",
      scope: "os",
      layer: "policy",
      tool: "node-script",
      commandPreview: "node scripts/check-tool-governance-final.js",
      description: "Tool/MCP governance checks: validate tool registry, MCP registry, permission matrix, and gateway.",
      requiresApproval: false,
      requiresRunner: false,
      riskLevel: "low",
      costClass: "free",
      evidenceTypes: ["tool-governance-report"],
      ownerAgent: "AUDITOR",
      changedFilePatterns: ["tool-governance/**"],
      forbiddenInDemo: false,
      dataClassification: "public",
      executionEnabled: false,
      allowedInMode: ["preview", "controlled"],
      status: "ready",
    },
    {
      suiteId: "os-trigger-gateway-checks",
      osScope: "nexus-os",
      scope: "os",
      layer: "api",
      tool: "node-script",
      commandPreview: "node scripts/check-trigger-integration-final.js",
      description: "Trigger gateway checks: validate manual, scheduled, GitHub, ticket, and chat trigger previews.",
      requiresApproval: false,
      requiresRunner: false,
      riskLevel: "low",
      costClass: "free",
      evidenceTypes: ["trigger-gateway-report"],
      ownerAgent: "AUDITOR",
      changedFilePatterns: ["trigger-gateway/**", "integrations/**"],
      forbiddenInDemo: false,
      dataClassification: "public",
      executionEnabled: false,
      allowedInMode: ["preview", "controlled"],
      status: "ready",
    },
    {
      suiteId: "os-api-batch-adapter-checks",
      osScope: "nexus-os",
      scope: "os",
      layer: "api",
      tool: "node-script",
      commandPreview: "node scripts/check-api-batch-final.js",
      description: "API/batch adapter checks: validate provider adapter, batch job builder, JSONL, status, reconciliation, and cost estimator.",
      requiresApproval: false,
      requiresRunner: false,
      riskLevel: "low",
      costClass: "free",
      evidenceTypes: ["api-batch-report"],
      ownerAgent: "AUDITOR",
      changedFilePatterns: ["api-batch/**"],
      forbiddenInDemo: false,
      dataClassification: "public",
      executionEnabled: false,
      allowedInMode: ["preview", "controlled"],
      status: "ready",
    },
    {
      suiteId: "os-db-foundation-checks",
      osScope: "nexus-os",
      scope: "os",
      layer: "db",
      tool: "node-script",
      commandPreview: "node scripts/check-db-foundation.js",
      description: "DB foundation checks: validate schema stubs, durable state readiness, and write-disabled policy.",
      requiresApproval: false,
      requiresRunner: false,
      riskLevel: "low",
      costClass: "free",
      evidenceTypes: ["db-foundation-report"],
      ownerAgent: "AUDITOR",
      changedFilePatterns: ["db/**"],
      forbiddenInDemo: false,
      dataClassification: "public",
      executionEnabled: false,
      allowedInMode: ["preview", "controlled"],
      status: "ready",
    },
    {
      suiteId: "os-activity-observability-checks",
      osScope: "nexus-os",
      scope: "os",
      layer: "runtime",
      tool: "node-script",
      commandPreview: "node scripts/check-activity-observability-final.js",
      description: "Activity observability checks: validate event schema, logger, capture, and trace view.",
      requiresApproval: false,
      requiresRunner: false,
      riskLevel: "low",
      costClass: "free",
      evidenceTypes: ["observability-report"],
      ownerAgent: "AUDITOR",
      changedFilePatterns: ["observability/**"],
      forbiddenInDemo: false,
      dataClassification: "public",
      executionEnabled: false,
      allowedInMode: ["preview", "controlled"],
      status: "ready",
    },
    {
      suiteId: "os-docs-diagram-readability-checks",
      osScope: "nexus-os",
      scope: "os",
      layer: "docs",
      tool: "node-script",
      commandPreview: "node scripts/check-docs-coverage.js && node scripts/check-format-readability.js",
      description: "Docs/diagram/readability checks: validate docs coverage, architecture diagrams, and line length.",
      requiresApproval: false,
      requiresRunner: false,
      riskLevel: "low",
      costClass: "free",
      evidenceTypes: ["docs-check-report"],
      ownerAgent: "AUDITOR",
      changedFilePatterns: ["docs/**"],
      forbiddenInDemo: false,
      dataClassification: "public",
      executionEnabled: false,
      allowedInMode: ["preview", "controlled"],
      status: "ready",
    },
  ];

  return suites.map((s) => normalizeTestSuiteRecord(s));
}

/**
 * Validate an array of OS test suite records.
 */
export function validateOsTestSuites(suites) {
  const errors = [];
  if (!Array.isArray(suites)) {
    errors.push("suites must be an array.");
    return { valid: false, errors };
  }
  for (const suite of suites) {
    const result = validateTestSuiteRecord(suite);
    if (!result.valid) {
      errors.push(...result.errors.map((e) => `[${suite.suiteId || "unknown"}] ${e}`));
    }
    if (suite.executionEnabled !== false) {
      errors.push(`[${suite.suiteId}] executionEnabled must be false.`);
    }
    if (suite.scope !== "os" && suite.scope !== "cross_cutting") {
      errors.push(`[${suite.suiteId}] OS suite scope must be 'os' or 'cross_cutting'.`);
    }
  }
  return { valid: errors.length === 0, errors };
}

/**
 * Summarize a list of OS test suite records.
 */
export function summarizeOsTestSuites(suites) {
  if (!Array.isArray(suites)) return { total: 0, byLayer: {}, byTool: {}, executionEnabled: false };
  const byLayer = {};
  const byTool = {};
  for (const suite of suites) {
    byLayer[suite.layer] = (byLayer[suite.layer] || 0) + 1;
    byTool[suite.tool] = (byTool[suite.tool] || 0) + 1;
  }
  return {
    total: suites.length,
    byLayer,
    byTool,
    executionEnabled: false,
    ownerAgents: [...new Set(suites.map((s) => s.ownerAgent).filter(Boolean))],
  };
}
