const ALLOW_RULES = Object.freeze([
  {
    category: "project_source",
    roots: ["projects/*/src/", "projects/*/app/", "projects/*/lib/", "projects/*/components/"],
    description: "Project-owned source files.",
  },
  {
    category: "project_docs",
    roots: ["projects/*/README.md", "projects/*/docs/"],
    description: "Project-owned documentation.",
  },
  {
    category: "project_tests",
    roots: ["projects/*/test/", "projects/*/tests/", "projects/*/__tests__/"],
    description: "Project-owned test files.",
  },
  {
    category: "project_config",
    roots: [
      "projects/*/package.json",
      "projects/*/tsconfig.json",
      "projects/*/vite.config.js",
      "projects/*/next.config.js",
      "projects/*/eslint.config.js",
      "projects/*/nexus.project.json",
    ],
    description: "Project build and validation configuration.",
  },
  {
    category: "redacted_release_manifest",
    roots: ["artifacts/project-release/private-project-release-manifest.json"],
    description: "Redacted release manifest generated by NEXUS.",
    requiresRedaction: true,
  },
  {
    category: "redacted_validation_summary",
    roots: ["reports/private-validation-snapshot.md", "reports/project-validation-summary.md"],
    description: "Redacted validation summary for release review.",
    requiresRedaction: true,
  },
]);

const DENY_RULES = Object.freeze([
  { category: "nexus_agents", roots: ["agents/"], reason: "NEXUS agents are OS internals." },
  { category: "nexus_skills", roots: ["skills/"], reason: "NEXUS skills are OS internals." },
  { category: "nexus_hooks", roots: ["hooks/"], reason: "NEXUS hooks are OS internals." },
  { category: "nexus_tools", roots: ["tools/"], reason: "NEXUS tools are OS internals." },
  { category: "nexus_policy", roots: ["policy/"], reason: "NEXUS policies are not project package content." },
  { category: "local_state", roots: ["local-state/", "runtime/"], reason: "Runtime state must not be exported." },
  { category: "observability_logs", roots: ["observability/", "logs/"], reason: "Raw logs must remain local." },
  { category: "os_roadmap", roots: ["os-roadmap/"], reason: "NEXUS OS roadmap is control-plane content." },
  { category: "providers", roots: ["providers/"], reason: "Provider adapters are OS internals." },
  { category: "orchestrator", roots: ["orchestrator/"], reason: "Orchestrator runtime is OS internal." },
  { category: "db", roots: ["db/"], reason: "DB foundation files are OS internals." },
  { category: "command_center", roots: ["dashboard/"], reason: "Command Center source is OS internal." },
  { category: "raw_evidence", roots: ["evidence/", "audit/", "activity/"], reason: "Raw evidence, audit, and activity ledgers must not be exported." },
  { category: "memory", roots: ["memory/"], reason: "Memory records are not project package content." },
  { category: "secrets", roots: [".env", ".env.", "secrets/", "credentials/", "keys/"], reason: "Secrets are never exportable." },
  { category: "secret_extensions", roots: [".pem", ".p12", ".key"], reason: "Key material is never exportable.", matchMode: "suffix" },
  { category: "demo_data", roots: ["demo/"], reason: "Demo data is not project package content unless explicitly exporting demo mode." },
  {
    category: "private_reports",
    roots: ["reports/raw/", "reports/private/", "reports/evidence/", "reports/audit/"],
    reason: "Reports must be redacted and explicitly allow-listed before export.",
  },
]);

function normalizePath(pathname) {
  return String(pathname || "").replaceAll("\\", "/").replace(/^\.\//, "").trim();
}

function matchesRoot(pathname, root, matchMode = "prefix") {
  if (matchMode === "suffix") return pathname.endsWith(root);
  if (root.includes("*")) {
    const escaped = root
      .split("*")
      .map((part) => part.replace(/[.+?^${}()|[\]\\]/g, "\\$&"))
      .join("[^/]+");
    return new RegExp(`^${escaped}`).test(pathname);
  }
  if (root.endsWith("/")) return pathname.startsWith(root);
  return pathname === root || pathname.startsWith(`${root}/`) || pathname.startsWith(root);
}

function cloneRule(rule) {
  return {
    ...rule,
    roots: [...rule.roots],
  };
}

export function getProjectExportAllowRules() {
  return ALLOW_RULES.map(cloneRule);
}

export function getProjectExportDenyRules() {
  return DENY_RULES.map(cloneRule);
}

export function matchProjectExportRule(pathname, rules) {
  const normalizedPath = normalizePath(pathname);
  return rules.find((rule) => rule.roots.some((root) => matchesRoot(normalizedPath, root, rule.matchMode)));
}

export function validateExportRules(rules = {}) {
  const errors = [];
  const allowRules = Array.isArray(rules.allowRules) ? rules.allowRules : ALLOW_RULES;
  const denyRules = Array.isArray(rules.denyRules) ? rules.denyRules : DENY_RULES;

  for (const [label, entries] of [
    ["allowRules", allowRules],
    ["denyRules", denyRules],
  ]) {
    if (!Array.isArray(entries) || entries.length === 0) errors.push(`${label} must be a non-empty array`);
    for (const entry of entries) {
      if (!entry.category) errors.push(`${label} entry missing category`);
      if (!Array.isArray(entry.roots) || entry.roots.length === 0) errors.push(`${entry.category || label} missing roots`);
    }
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}
