import { buildModeGuardResult } from "./modeGuard.js";
import { summarizeRedaction } from "./redaction.js";
import { createPassResult, validateResultEnvelope } from "./resultEnvelope.js";
import {
  RELEASE_DEPLOY_EXPORT_PACKAGE_MODEL_PHASE,
  RELEASE_DEPLOY_EXPORT_PACKAGE_SAFETY_FLAG_NAMES,
  buildReleaseDeployExportPackageModel,
  validateReleaseDeployExportPackageModel,
} from "./releaseDeployExportPackageModel.js";

export const RELEASE_DEPLOY_EXPORT_PACKAGE_PREVIEW_PHASE = "P143.3";
export const RELEASE_DEPLOY_EXPORT_PACKAGE_PREVIEW_VERSION = "1.0";
export const RELEASE_DEPLOY_EXPORT_PACKAGE_PREVIEW_SAFETY_FLAG_NAMES = RELEASE_DEPLOY_EXPORT_PACKAGE_SAFETY_FLAG_NAMES;

const OWNER_CAPABILITY = "NEXUS Release Deploy Export Package Preview Guard";
const DEFAULT_REPORT_REF = "reports/p1433-release-deploy-export-package-pipeline-report.md";
const DEFAULT_ACTIVITY_REF = "os-roadmap/phase-status.json#P143.3";
const DISABLED_REASON = "P143.3 produces a display-safe, non-runnable shipping preview. Release package creation, deploy start, rollback execution, export execution, package build, patch application, build/test execution, DB/runtime writes, provider/model calls, tool execution, MCP startup, agent dispatch, project mutation, network calls, and spend remain blocked.";

function blockedSafetyFlags() {
  return Object.fromEntries(RELEASE_DEPLOY_EXPORT_PACKAGE_PREVIEW_SAFETY_FLAG_NAMES.map((flag) => [flag, false]));
}

function normalizeText(value = "", fallback = "") {
  const normalized = String(value || "").trim();
  return normalized || fallback;
}

function asArray(value = []) {
  if (Array.isArray(value)) return value.filter(Boolean).map((item) => String(item));
  if (value === undefined || value === null || value === "") return [];
  return [String(value)];
}

function uniqueList(values = []) {
  return [...new Set(asArray(values))];
}

function displayRef(prefix, sequence) {
  return `${prefix}-${Number.isFinite(Number(sequence)) ? Number(sequence) : 1}`;
}

function evidenceRefs(extra = []) {
  return uniqueList([DEFAULT_REPORT_REF, ...asArray(extra)]);
}

function activityRefs(extra = []) {
  return uniqueList([DEFAULT_ACTIVITY_REF, ...asArray(extra)]);
}

function buildCostImpact() {
  return {
    estimatedUsd: 0,
    actualUsd: 0,
    releaseJobsAllowed: false,
    deployJobsAllowed: false,
    exportJobsAllowed: false,
    packageJobsAllowed: false,
    networkCallsAllowed: false,
    providerSpendAllowed: false,
  };
}

function hasUnsafeIdentifier(value) {
  return /(?:project|private|token|tenant|workspace|founder|session|user|role|permission|access|secret|provider|tool|agent|memory|policy|release|deploy|export|package|rollback|artifact|provenance)_[A-Za-z0-9_-]*\d[A-Za-z0-9_-]*/i.test(JSON.stringify(value));
}

function sourceFields(source = {}, sourceType = "", sequence = 1) {
  const sourceRef = source.gateRef || source.targetRef || source.artifactRef || source.provenanceRef || source.rollbackRef || displayRef("shipping-source", sequence);
  return {
    sourceRef,
    displayName: source.displayName || `${sourceType.replace(/_/g, " ")} preview`,
    currentState: source.currentState || source.captureState || source.previewState || "blocked_preview",
    nextAction: source.nextAction || "Review this preview row before any future shipping authority is considered.",
    blockers: source.blockers || [DISABLED_REASON],
    ownerCapability: source.ownerCapability || OWNER_CAPABILITY,
    evidenceRefs: source.evidenceRefs,
    activityRefs: source.activityRefs,
    costImpact: source.costImpact,
    authorityFlags: source.authorityFlags,
  };
}

export function buildPreviewRow(input = {}) {
  const sequence = Number.isFinite(Number(input.sequence)) ? Number(input.sequence) : 1;
  const sourceType = normalizeText(input.sourceType, "shipping_review");
  const source = sourceFields(input.source || {}, sourceType, sequence);
  const flags = blockedSafetyFlags();
  const row = {
    rowRef: normalizeText(input.rowRef, displayRef("shipping-preview-row", sequence)),
    schemaVersion: RELEASE_DEPLOY_EXPORT_PACKAGE_PREVIEW_VERSION,
    phase: RELEASE_DEPLOY_EXPORT_PACKAGE_PREVIEW_PHASE,
    sourceModelPhase: RELEASE_DEPLOY_EXPORT_PACKAGE_MODEL_PHASE,
    sourceType,
    sourceRef: normalizeText(input.sourceRef, source.sourceRef),
    displayName: normalizeText(input.displayName, source.displayName),
    currentState: normalizeText(input.currentState, source.currentState),
    previewState: "blocked_dry_run_ready_for_review",
    nextAction: normalizeText(input.nextAction, source.nextAction),
    blockers: uniqueList([
      ...asArray(source.blockers),
      ...asArray(input.blockers),
      "Executable payloads are not generated by this preview.",
      DISABLED_REASON,
    ]),
    ownerCapability: normalizeText(input.ownerCapability, source.ownerCapability),
    disabledReason: DISABLED_REASON,
    previewOnly: true,
    readOnly: true,
    localOnly: true,
    executionAllowed: false,
    executablePayload: null,
    deployPayload: null,
    exportPayload: null,
    packagePayload: null,
    rollbackPayload: null,
    providerPayload: null,
    toolPayload: null,
    projectMutationPayload: null,
    dbRuntimeMutationPayload: null,
    rawPayloadVisible: false,
    rawPrivateIdsVisible: false,
    rawInternalPayloadsVisible: false,
    evidenceRefs: evidenceRefs(input.evidenceRefs || source.evidenceRefs),
    activityRefs: activityRefs(input.activityRefs || source.activityRefs),
    costImpact: {
      ...buildCostImpact(),
      ...source.costImpact,
      estimatedUsd: 0,
      actualUsd: 0,
      providerSpendAllowed: false,
      networkCallsAllowed: false,
    },
    authorityFlags: {
      ...flags,
      ...(source.authorityFlags || {}),
      ...flags,
    },
    safetyFlags: flags,
    ...flags,
  };
  return row;
}

export function validatePreviewRow(row = {}) {
  const errors = [];
  for (const field of ["rowRef", "sourceType", "sourceRef", "displayName", "currentState", "previewState", "nextAction", "blockers", "ownerCapability", "disabledReason", "evidenceRefs", "activityRefs", "costImpact", "authorityFlags", "safetyFlags"]) {
    if (!(field in row)) errors.push(`${field} is required`);
  }
  if (row.phase !== RELEASE_DEPLOY_EXPORT_PACKAGE_PREVIEW_PHASE) errors.push("phase must be P143.3");
  if (row.sourceModelPhase !== RELEASE_DEPLOY_EXPORT_PACKAGE_MODEL_PHASE) errors.push("sourceModelPhase must be P143.2");
  if (row.previewOnly !== true || row.readOnly !== true || row.localOnly !== true) errors.push("row must remain local read-only preview metadata");
  if (row.executionAllowed !== false) errors.push("executionAllowed must remain false");
  for (const field of ["executablePayload", "deployPayload", "exportPayload", "packagePayload", "rollbackPayload", "providerPayload", "toolPayload", "projectMutationPayload", "dbRuntimeMutationPayload"]) {
    if (row[field] !== null) errors.push(`${field} must be null`);
  }
  if (row.rawPayloadVisible !== false || row.rawPrivateIdsVisible !== false || row.rawInternalPayloadsVisible !== false) errors.push("row must hide raw internals");
  if (!Array.isArray(row.blockers) || row.blockers.length < 2) errors.push("blockers must explain blocked authority");
  if (!Array.isArray(row.evidenceRefs) || row.evidenceRefs.length === 0) errors.push("evidenceRefs are required");
  if (!Array.isArray(row.activityRefs) || row.activityRefs.length === 0) errors.push("activityRefs are required");
  if (row.costImpact?.estimatedUsd !== 0 || row.costImpact?.actualUsd !== 0 || row.costImpact?.providerSpendAllowed !== false || row.costImpact?.networkCallsAllowed !== false) errors.push("costImpact must remain zero-spend and local-only");
  for (const flag of RELEASE_DEPLOY_EXPORT_PACKAGE_PREVIEW_SAFETY_FLAG_NAMES) {
    if (row[flag] !== false) errors.push(`${flag} must be false`);
    if (row.safetyFlags?.[flag] !== false) errors.push(`safetyFlags.${flag} must be false`);
    if (row.authorityFlags?.[flag] !== false) errors.push(`authorityFlags.${flag} must be false`);
  }
  if (!/remain blocked/i.test(row.disabledReason || "")) errors.push("disabledReason must explain blocked authority");
  if (hasUnsafeIdentifier(row)) errors.push("row must not expose raw private identifiers");
  const serialized = JSON.stringify(row);
  if (/create release now|create package now|start deploy now|deploy now|run rollback now|rollback now|run export now|export now|package now|apply patch now|run build now|run tests now|write db now|call provider now|run tool now|dispatch agent now|mutate project now|spend now/i.test(serialized)) errors.push("row must not expose fake runnable actions");
  if (/raw json|raw logs|raw policy dump|raw release payload|raw deploy payload|raw export payload|raw package payload|raw provenance payload/i.test(serialized)) errors.push("row must not expose raw dumps");
  return { valid: errors.length === 0, errors };
}

function buildPreviewRows(sourceModel = {}) {
  const rows = [];
  for (const [sourceType, collection] of [
    ["release_gate", sourceModel.releaseGates || []],
    ["deploy_target", sourceModel.deployTargets || []],
    ["export_package", sourceModel.exportPackages || []],
    ["provenance_record", sourceModel.provenanceRecords || []],
    ["rollback_plan", sourceModel.rollbackPlans || []],
  ]) {
    for (const source of collection) {
      rows.push(buildPreviewRow({
        sequence: rows.length + 1,
        sourceType,
        source,
        evidenceRefs: sourceModel.evidenceRefs,
        activityRefs: sourceModel.activityRefs,
      }));
    }
  }
  return rows;
}

function buildPreviewSections(rows = []) {
  return [
    {
      sectionRef: "release-readiness-preview",
      label: "Release readiness preview",
      rowCount: rows.filter((row) => row.sourceType === "release_gate").length,
      blockedCount: rows.filter((row) => row.sourceType === "release_gate").length,
      nextAction: "Review release gates without creating release packages.",
    },
    {
      sectionRef: "deploy-export-package-preview",
      label: "Deploy, export, and package preview",
      rowCount: rows.filter((row) => ["deploy_target", "export_package"].includes(row.sourceType)).length,
      blockedCount: rows.filter((row) => ["deploy_target", "export_package"].includes(row.sourceType)).length,
      nextAction: "Review deploy/export/package posture without executable payloads.",
    },
    {
      sectionRef: "provenance-rollback-preview",
      label: "Provenance and rollback preview",
      rowCount: rows.filter((row) => ["provenance_record", "rollback_plan"].includes(row.sourceType)).length,
      blockedCount: rows.filter((row) => ["provenance_record", "rollback_plan"].includes(row.sourceType)).length,
      nextAction: "Review provenance and rollback posture without signing, exporting, or executing rollback.",
    },
  ];
}

function buildReadinessSummary(rows = [], sourceModel = {}) {
  return {
    sourceModelPhase: sourceModel.phase,
    rowCount: rows.length,
    blockedRowCount: rows.length,
    runnableActionCount: 0,
    releasePackageCreationCandidateCount: 0,
    deployStartCandidateCount: 0,
    exportExecutionCandidateCount: 0,
    packageBuildCandidateCount: 0,
    rollbackExecutionCandidateCount: 0,
    dbRuntimeWriteCandidateCount: 0,
    providerModelCallCandidateCount: 0,
    toolExecutionCandidateCount: 0,
    projectMutationCandidateCount: 0,
    networkCallCandidateCount: 0,
    providerSpendCandidateCount: 0,
    nextAction: "Route P143.3 preview to P143.4 Command Center UX without enabling shipping authority.",
  };
}

export function buildReleaseDeployExportPackagePreview(input = {}) {
  const sourceModel = input.sourceModel || input.model || buildReleaseDeployExportPackageModel(input);
  const sourceValidation = validateReleaseDeployExportPackageModel(sourceModel);
  const rows = sourceValidation.valid ? buildPreviewRows(sourceModel) : [];
  const flags = blockedSafetyFlags();
  const redaction = summarizeRedaction({ rows });
  return {
    phase: RELEASE_DEPLOY_EXPORT_PACKAGE_PREVIEW_PHASE,
    schemaVersion: RELEASE_DEPLOY_EXPORT_PACKAGE_PREVIEW_VERSION,
    mode: "display-safe-release-deploy-export-package-preview",
    sourceModelPhase: sourceModel.phase,
    sourceModelValid: sourceValidation.valid,
    sourceModelErrors: sourceValidation.errors,
    previewOnly: true,
    readOnly: true,
    localOnly: true,
    dryRunOnly: true,
    commandCenterVisible: true,
    currentState: "shipping_preview_ready_execution_blocked",
    modeGuard: buildModeGuardResult(input.mode || "public-safe", ["public-safe", "local-private", "test"]),
    ownerCapability: OWNER_CAPABILITY,
    rows,
    previewRows: rows,
    previewSections: buildPreviewSections(rows),
    readinessSummary: buildReadinessSummary(rows, sourceModel),
    blockers: [
      "Release package creation and package build remain blocked.",
      "Deploy start, rollback execution, export execution, patch application, and build/test execution remain blocked.",
      "Project mutation, DB/runtime writes, provider/model calls, tool execution, MCP startup, agent dispatch, network calls, and spend remain blocked.",
    ],
    disabledReason: DISABLED_REASON,
    nextAction: "Route this non-runnable shipping preview to P143.4 Command Center UX without creating packages, starting deploys, running exports, or executing rollback.",
    evidenceRefs: evidenceRefs(input.evidenceRefs || sourceModel.evidenceRefs),
    activityRefs: activityRefs(input.activityRefs || sourceModel.activityRefs),
    costImpact: buildCostImpact(),
    redaction: {
      changed: redaction.changed,
      redactionCount: redaction.redactionCount,
      rawPrivateIdsVisible: false,
      rawInternalPayloadsVisible: false,
      credentialValuesVisible: false,
      storageUrlsVisible: false,
    },
    safetyFlags: flags,
    ...flags,
  };
}

export function validateReleaseDeployExportPackagePreview(preview = {}) {
  const errors = [];
  if (preview.phase !== RELEASE_DEPLOY_EXPORT_PACKAGE_PREVIEW_PHASE) errors.push("phase must be P143.3");
  if (preview.schemaVersion !== RELEASE_DEPLOY_EXPORT_PACKAGE_PREVIEW_VERSION) errors.push("schemaVersion must be 1.0");
  if (preview.mode !== "display-safe-release-deploy-export-package-preview") errors.push("mode must be display-safe-release-deploy-export-package-preview");
  if (preview.sourceModelPhase !== RELEASE_DEPLOY_EXPORT_PACKAGE_MODEL_PHASE || preview.sourceModelValid !== true) errors.push("preview must consume a valid P143.2 source model");
  if (preview.previewOnly !== true || preview.readOnly !== true || preview.localOnly !== true || preview.dryRunOnly !== true) errors.push("preview must remain local read-only dry run metadata");
  if (preview.commandCenterVisible !== true) errors.push("preview must be available to Command Center projection");
  if (!preview.modeGuard?.ok) errors.push("mode guard must pass");
  if (!Array.isArray(preview.rows) || preview.rows.length < 12 || preview.rows !== preview.previewRows) errors.push("preview rows must be visible and reused as previewRows");
  for (const row of preview.rows || []) {
    const validation = validatePreviewRow(row);
    if (!validation.valid) errors.push(...validation.errors.map((error) => `${row.rowRef || "row"}: ${error}`));
  }
  if (!Array.isArray(preview.previewSections) || preview.previewSections.length < 3) errors.push("previewSections must summarize rows");
  if (preview.previewSections?.some((section) => section.blockedCount !== section.rowCount)) errors.push("all preview section rows must remain blocked");
  if (preview.readinessSummary?.rowCount !== preview.rows?.length || preview.readinessSummary?.blockedRowCount !== preview.rows?.length || preview.readinessSummary?.runnableActionCount !== 0) errors.push("readiness summary must keep rows blocked and non-runnable");
  for (const field of ["releasePackageCreationCandidateCount", "deployStartCandidateCount", "exportExecutionCandidateCount", "packageBuildCandidateCount", "rollbackExecutionCandidateCount", "dbRuntimeWriteCandidateCount", "providerModelCallCandidateCount", "toolExecutionCandidateCount", "projectMutationCandidateCount", "networkCallCandidateCount", "providerSpendCandidateCount"]) {
    if (preview.readinessSummary?.[field] !== 0) errors.push(`${field} must be zero`);
  }
  if (!Array.isArray(preview.blockers) || preview.blockers.length < 3) errors.push("blockers are required");
  if (!Array.isArray(preview.evidenceRefs) || preview.evidenceRefs.length === 0) errors.push("evidenceRefs are required");
  if (!Array.isArray(preview.activityRefs) || preview.activityRefs.length === 0) errors.push("activityRefs are required");
  if (preview.costImpact?.estimatedUsd !== 0 || preview.costImpact?.actualUsd !== 0 || preview.costImpact?.providerSpendAllowed !== false || preview.costImpact?.networkCallsAllowed !== false) errors.push("costImpact must remain zero-spend and local-only");
  if (preview.redaction?.rawPrivateIdsVisible !== false || preview.redaction?.rawInternalPayloadsVisible !== false || preview.redaction?.credentialValuesVisible !== false || preview.redaction?.storageUrlsVisible !== false) errors.push("redaction must hide internals, credential values, and storage URLs");
  for (const flag of RELEASE_DEPLOY_EXPORT_PACKAGE_PREVIEW_SAFETY_FLAG_NAMES) {
    if (preview[flag] !== false) errors.push(`${flag} must be false`);
    if (preview.safetyFlags?.[flag] !== false) errors.push(`safetyFlags.${flag} must be false`);
  }
  if (!/remain blocked/i.test(preview.disabledReason || "")) errors.push("disabledReason must explain blocked authority");
  if (!/without/i.test(preview.nextAction || "")) errors.push("nextAction must route forward without authority");
  if (hasUnsafeIdentifier(preview)) errors.push("preview must not expose raw private identifiers");
  const serialized = JSON.stringify(preview);
  if (/create release now|create package now|start deploy now|deploy now|run rollback now|rollback now|run export now|export now|package now|apply patch now|run build now|run tests now|write db now|call provider now|run tool now|dispatch agent now|mutate project now|spend now/i.test(serialized)) errors.push("preview must not expose fake runnable actions");
  if (/raw json|raw logs|raw policy dump|raw release payload|raw deploy payload|raw export payload|raw package payload|raw provenance payload/i.test(serialized)) errors.push("preview must not expose raw dumps");
  return { valid: errors.length === 0, errors };
}

export function buildReleaseDeployExportPackagePreviewEnvelope(input = {}) {
  const preview = input.preview || buildReleaseDeployExportPackagePreview(input);
  const validation = validateReleaseDeployExportPackagePreview(preview);
  const envelope = createPassResult({
    phase: RELEASE_DEPLOY_EXPORT_PACKAGE_PREVIEW_PHASE,
    mode: "display-safe-release-deploy-export-package-preview",
    source: "shared/releaseDeployExportPackagePreview.js",
    summary: validation.valid
      ? "P143.3 display-safe shipping preview is valid; release, deploy, export, package, rollback, project mutation, DB/runtime writes, provider/model calls, network calls, and spend remain blocked."
      : "P143.3 display-safe shipping preview is invalid.",
    data: { preview },
    warnings: validation.valid ? [] : validation.errors,
    evidence: preview.evidenceRefs || [],
  });
  const envelopeValidation = validateResultEnvelope(envelope);
  return {
    ...envelope,
    ok: validation.valid && envelopeValidation.valid,
    status: validation.valid && envelopeValidation.valid ? "PASS" : "FAIL",
    errors: [...validation.errors, ...envelopeValidation.errors],
    envelopeValid: envelopeValidation.valid,
    envelopeErrors: envelopeValidation.errors,
  };
}
